### ISSUE TITLE
App Crash on iOS13 when starting ROM Download

### ISSUE THREAD

**Issue by rafaelmaeuer** [CocoaBob/GBA4iOS#2]
When trying to start the download of a rom on iOS 13 the app crashes with this error:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason:
'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'

**Comment by CocoaBob** [comment]
Thank you for the feedback!

Let me check that after work, it should be an easy fix ;)

In the meantime if you still want to download a file, you could download them in Safari or any other 3rd party app like [Documents](https://apps.apple.com/app/id364901807), then import the files to GBA4iOS via Share panel.

**Comment by rafaelmaeuer** [comment]
It seems to happen in RSTDirectoryMonitor.m line 125 at 
```
dispatch_async(self.directory_monitor_queue, ^{})
```

**Comment by CocoaBob** [comment]
Great, that gives the clue, just submitted a quick fix, please try.

I didn't test it though 😅

**Comment by rafaelmaeuer** [comment]
nice on, this fixed it
