### ISSUE TITLE
Problem changing skins on iOS13

### ISSUE THREAD

**Issue by rafaelmaeuer** [CocoaBob/GBA4iOS#3]
When selecting the + on skins or checking for app updates I get the following error:
<img width="545" alt="Bildschirmfoto 2019-11-25 um 20 36 38" src="https://user-images.githubusercontent.com/6418459/69571956-6e318580-0fc3-11ea-91ce-3b9d815bb7fa.png">

**Comment by CocoaBob** [comment]
I just checked the code, it expects to receive a JSON file from this url `http://gba4iosapp.com/delta/controller_skins/root.json`, but the original author of GBA4iOS has removed that link, that's why we got an error here.

**Comment by CocoaBob** [comment]
But you still can download 3rd party skins from internet, for example https://gba4ios.online/gba4ios-skins, then drag & drop the files to your iOS device via iTunes File Sharing.

**Comment by rafaelmaeuer** [comment]
OK thank you, so what can we do about this. Do you have the contents of this file so we can host it somewhere else? I also want to change the default skin from purple to another color. I adapted everything from the default configuration in the purple skin folder and replaced Default .gbaskin and .gbcskin files in Xcode. But I get `Fixing corrupted default skin...` Error when opening skins in settings.

**Comment by rafaelmaeuer** [comment]
It seems that the identifier in the skins `info.json` is ignored. When modifying skin red to have the the identifier `com.GBA4iOS.default` nevertheless in the `Skins` directory the folder `com.GBA4iOS.default.red` is created. It's clear that the skin cannot be found then. But why is this happening?

**Comment by CocoaBob** [comment]
I don't know how the `info.json` looks like (I never checked that part before), but I think you could analyze his codes to do some reverse engineering, and also create your own JSON structure and parsing logic to meet your needs. For example, I think we only need `title`, `imageUrl`, `skinUrl` to show a title, an image and a download link. Then you can host the JSON file and some skin files somewhere, to let your users download them. Here's an example I created long time ago, to fit my iPhone X screen.
[iPhoneX.gbaskin.zip](https://github.com/CocoaBob/GBA4iOS/files/3892501/iPhoneX.gbaskin.zip)

**Comment by rafaelmaeuer** [comment]
Ok I found out, that the `. gbaskin` and `.gbcskin` files are basically zip files and get extracted when no file is found in skins folder. Needed to do the changes in the zip file and it works now.

**Comment by rafaelmaeuer** [comment]
I managed the reverse engineering, if anyone else wants to enable this have a look at:
https://github.com/rafaelmaeuer/GBA4iOS/blob/master/Skins/root.json
