### ISSUE TITLE
App crash on Dropbox Sync

### ISSUE THREAD

**Issue by rafaelmaeuer** [CocoaBob/GBA4iOS#4]
When activating Dropbox sync, after saving the first state the app crashes with:
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot read file at file:///var/mobile/Containers/Data/Application/9FDA6DC5-6436-4DFE-A7C1-DB183C4D3C4E/Library/Dropbox%20Sync/Upload%20History/Rafaels%20iPhone%20SE.plist'
```

**Comment by CocoaBob** [comment]
I'm not sure Dropbox SDK is still working, and it must be connected to the original author's Dropbox developer account (It needs an API Key). I don't have much time to investigate that, it's a little complicated 🤦‍♂️ Could you check that? Or maybe you can simply hide this feature in your release?

**Comment by rafaelmaeuer** [comment]
I will try to investigate this, as its a really cool feature to backup and share savegames

**Comment by clintonmedbery** [comment]
It looks like the dropbox initialization is commented out and if you uncomment it, it seems to use DropBox V1 API instead of the included Dropbox V2 Api.
GBASyncManager
```
   // TODO: - Uncomment
    //DBSession *session = [[DBSession alloc] initWithAppKey:@"obzx8requbc5bn5" appSecret:@"thdkvkp3hkbmpte" root:kDBRootAppFolder];
    //[DBSession setSharedSession:session];
```

DBSession is no longer used. I updated it to use DBUserClient but it doesn't seem to be working. Looks like those tokens are used elsewhere. I don't really do Objective C but I might be able to look later if I have time.

**Comment by TheRojam** [comment]
There are still Dropbox SDK for [ObjectiveC](https://www.dropbox.com/developers/documentation/objective-c) and also for [swift](https://www.dropbox.com/developers/documentation/swift). 
If you know whats needed to update these API Keys i would like to support in that way.
I think also a great alternative/implementation would be gDrive or may better iCloud.

**Comment by rafaelmaeuer** [comment]
It seems the only necessary thing to get in running, is to generate a new dropbox app key, and replace it in GBAAppDelegate.mm and Info.plist for Device and Simulator.

```
// GBAAppDelegate.mm (Line 82)
[DBClientsManager setupWithAppKey:@"obzx8requbc5bn5"];  // Setup Dropbox

// Info.plist (Line 127)
<string>db-obzx8requbc5bn5</string>
```
