### ISSUE TITLE
Is Wireless Linking (Beta) working with Pokemon Cable Club?

### ISSUE THREAD

**Issue by rafaelmaeuer** [CocoaBob/GBA4iOS#8]
Hey I successfully managed to connect two devices with the implemented Wireless Linking feature, but I cannot establish a connection in the Pokemon Cable Club.

I ensured that both games have the same language, received the pokedex and passed the first arena. Its not working - just complains that this area is reserved for 2 friends using link cable.

Has anyone successfully done this?

**Comment by rafaelmaeuer** [comment]
According to Rileys [tweet](https://twitter.com/rileytestut/status/454318993063432192) and [blogpost](http://rileytestut.com/blog/2014/10/08/gba4ios-is-dead-long-live-gba4ios/) this should be possible with some performance issues. But all screenshots show pokemon leaf-green, fire-red or later. Has anyone tried it with the original blue or red version?

**Comment by amachairidis** [comment]
> According to Rileys [tweet](https://twitter.com/rileytestut/status/454318993063432192) and [blogpost](http://rileytestut.com/blog/2014/10/08/gba4ios-is-dead-long-live-gba4ios/) this should be possible with some performance issues. But all screenshots show pokemon leaf-green, fire-red or later. Has anyone tried it with the original blue or red version?

The feature is simulating the wireless connection. Not the cabled one. 
So it only works on games that had the Wireless Adapter/Club.

**Comment by rafaelmaeuer** [comment]
thanks for clarifying this
